name: Reusable Docker Image Test and Build Workflow

permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: "The name of the image to build (e.g. project/repo/image)"
      dockerfile_path:
        required: false
        type: string
        default: "./Dockerfile"
        description: "Path to Dockerfile"
      build_context:
        required: false
        type: string
        default: "."
        description: "Build context"
      registry_host:
        required: false
        type: string
        description: "GAR Registry Host (e.g. us-central1-docker.pkg.dev)"
      environment:
        required: true
        type: string
        description: "Environment (e.g. dev, qa, prod)"
    outputs:
      image_name:
        description: "The full image name with tag"
        value: ${{ jobs.build.outputs.image_name }}

jobs:
  build:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      image_name: ${{ steps.setup-base.outputs.registry_host }}/${{ inputs.image_name }}:${{ steps.version.outputs.version }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get ref
        id: get-ref
        uses: actions/github-script@v8
        with:
          script: |
            const idToken = await core.getIDToken()
            const payloadBase64 = idToken.split('.')[1];
            const payloadJson = Buffer.from(payloadBase64, 'base64').toString('utf-8');
            const payload = JSON.parse(payloadJson);
            const workflowRef = payload.job_workflow_ref;
            console.log(`Full workflow ref from token: ${workflowRef}`);
            const ref = workflowRef.split('@')[1].replace('refs/heads/', '');
            console.log(`Resolved library ref: ${ref}`);
            core.setOutput('ref', ref);
      
      - name: Checkout base-workflows
        uses: actions/checkout@v4
        with:
          repository: nirojasmar/base-workflows
          ref: ${{ steps.get-ref.outputs.ref }}
          path: base-workflows
          persist-credentials: false

      - name: Set up Base
        id: setup-base
        uses: ./base-workflows/actions/setup-base/
        with:
          environment: ${{ inputs.environment }}

      - name: Calculate Version
        id: version
        uses: ./base-workflows/actions/version/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export for Scan
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          load: true
          tags: ${{ steps.setup-base.outputs.registry_host }}/${{ inputs.image_name }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.setup-base.outputs.registry_host }}/${{ inputs.image_name }}:test
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build and Push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ${{ steps.setup-base.outputs.registry_host }}/${{ inputs.image_name }}:${{ steps.version.outputs.version }}
            ${{ steps.setup-base.outputs.registry_host }}/${{ inputs.image_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max